### ISSUE TITLE
客户端解析失败，显示服务器不可用

### ISSUE THREAD

**Issue by hyb-oyqq** [pchpub/BiliRoaming-Rust-Server#123]
客户端解析失败，显示服务器不可用
```
thread 'actix-server worker 0' panicked at 'called `Option::unwrap()` on a `None` value', src/mods/types.rs:206:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-server worker 1' panicked at 'called `Option::unwrap()` on a `None` value', src/mods/types.rs:206:26
thread 'actix-server worker 2' panicked at 'called `Option::unwrap()` on a `None` value', src/mods/types.rs:206:26
thread 'actix-server worker 3' panicked at 'called `Option::unwrap()` on a `None` value', src/mods/types.rs:206:26 
```

debug日志
```
[2023-09-11 14:57:55][ INFO] 你好喵~
[Warning] config.json 更新失败
[2023-09-11 14:57:55][ INFO] starting 8 workers
[2023-09-11 14:57:55][ INFO] Tokio runtime found; starting in existing Tokio runtime
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:57:55][ERROR] Specified path is not a directory: "./web/"
[2023-09-11 14:58:01][DEBUG] starting new connection: https://app.bilibili.com/
[2023-09-11 14:58:01][DEBUG] resolving host="app.bilibili.com"
[2023-09-11 14:58:01][DEBUG] connecting to 103.151.151.5:443
[2023-09-11 14:58:01][DEBUG] connected to 103.151.151.5:443
[2023-09-11 14:58:01][DEBUG] No cached session for DnsName(DnsName(DnsName("app.bilibili.com")))
[2023-09-11 14:58:01][DEBUG] Not resuming any session
[2023-09-11 14:58:01][DEBUG] ALPN protocol is Some(b"h2")
[2023-09-11 14:58:01][DEBUG] Using ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[2023-09-11 14:58:01][DEBUG] Server supports tickets
[2023-09-11 14:58:01][DEBUG] ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp256r1 }
[2023-09-11 14:58:01][DEBUG] Server DNS name is DnsName(DnsName(DnsName("app.bilibili.com")))
[2023-09-11 14:58:01][DEBUG] Session saved
[2023-09-11 14:58:01][DEBUG] binding client connection
[2023-09-11 14:58:01][DEBUG] client connection bound
[2023-09-11 14:58:01][DEBUG] send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
[2023-09-11 14:58:01][DEBUG] Connection; peer=Client
[2023-09-11 14:58:01][DEBUG] send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
[2023-09-11 14:58:01][DEBUG] pooling idle connection for ("https", app.bilibili.com)
[2023-09-11 14:58:01][DEBUG] send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
[2023-09-11 14:58:01][DEBUG] received frame=Settings { flags: (0x0), max_concurrent_streams: 128, initial_window_size: 65536, max_frame_size: 16777215 }
[2023-09-11 14:58:01][DEBUG] send frame=Settings { flags: (0x1: ACK) }
[2023-09-11 14:58:01][DEBUG] received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 2147418112 }
[2023-09-11 14:58:01][DEBUG] received frame=Settings { flags: (0x1: ACK) }
[2023-09-11 14:58:01][DEBUG] received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
[2023-09-11 14:58:01][DEBUG] received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
[2023-09-11 14:58:01][DEBUG] received frame=Data { stream_id: StreamId(1) }
[2023-09-11 14:58:01][DEBUG] [GET WEBPAGE] PROXY false |  -> STATUS CODE: 200
[2023-09-11 14:58:01][DEBUG] [GET WEBPAGE] URL https://app.bilibili.com/x/v2/account/myinfo?access_key=2f7149802e00fddbf412974d19b67891&appkey=1d8b6e7d45233436&build=5360000&mobi_app=android&platform=android&ts=1694444281&sign=e305a1c83e27bb468f14f48a721eae6a
[2023-09-11 14:58:01][DEBUG] [UPDATE_CACHE] UID 23579215 | AK 2f7149802e00fddbf412974d19b67891 -> is VIP: true. New user_info cache data: {"code":0,"access_key":"2f7149802e00fddbf412974d19b67891","uid":23579215,"vip_expire_time":1730649600000,"expire_time":1696604281121}
[2023-09-11 14:58:01][DEBUG] send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
[2023-09-11 14:58:01][DEBUG] Connection::poll; connection error error=GoAway(b"", NO_ERROR, Library)
[2023-09-11 14:58:01][DEBUG] Sending warning alert CloseNotify
thread 'actix-server worker 0' panicked at 'called `Option::unwrap()` on a `None` value', src/mods/types.rs:206:26
stack backtrace:
   0:     0x7fbdde4aff90 - std::backtrace_rs::backtrace::libunwind::trace::hbcfab3fd053d4f9c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fbdde4aff90 - std::backtrace_rs::backtrace::trace_unsynchronized::h7e10f1e6f3c9da4a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbdde4aff90 - std::sys_common::backtrace::_print_fmt::h0eb15397837ad542
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fbdde4aff90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf7c1fab2895a69f6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fbdde2135ae - core::fmt::write::h2f4df54048f9b2f6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x7fbdde489bc4 - std::io::Write::write_fmt::he2a3d151c8582691
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x7fbdde4b179f - std::sys_common::backtrace::_print::h99e54e0cdbaf7634
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fbdde4b179f - std::sys_common::backtrace::print::h55b70014ea5d5cc4
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fbdde4b139f - std::panicking::default_hook::{{closure}}::hfd59080aa8766eb0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x7fbdde4b241d - std::panicking::default_hook::h5edea27902e76e98
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x7fbdde4b241d - std::panicking::rust_panic_with_hook::he30378b37a10c21d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x7fbdde4b1eb4 - std::panicking::begin_panic_handler::{{closure}}::h4870022cb9a556d9
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:577:13
  12:     0x7fbdde4b1e4c - std::sys_common::backtrace::__rust_end_short_backtrace::h1c949acb60f0c2aa
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7fbdde4b1e21 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x7fbdddef13c2 - core::panicking::panic_fmt::hc3a21bf3fce4f929
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x7fbdddef14bc - core::panicking::panic::ha93ad6cb648d74fd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
  16:     0x7fbdde1dba68 - biliroaming_rust_server::mods::cache::update_user_info_cache::{{closure}}::hf281284fa33d1594
  17:     0x7fbdde1d203b - biliroaming_rust_server::mods::upstream_res::get_upstream_bili_account_info_rec::{{closure}}::h9d094ba4e9b3e858
  18:     0x7fbdddfa3ab5 - biliroaming_rust_server::mods::user_info::get_user_info::{{closure}}::ha4e74effe6cc0bf8
  19:     0x7fbdddf9481c - biliroaming_rust_server::mods::handler::handle_playurl_request::{{closure}}::hf673c91587eb30ea
  20:     0x7fbdde070a14 - actix_web::handler::handler_service::{{closure}}::{{closure}}::h216788b73de3a415
  21:     0x7fbdde06bda8 - <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}::hab147ca2d10f8436
  22:     0x7fbdde06cdef - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::hcc57d36176248111
  23:     0x7fbdddf0fcb9 - <actix_service::map_err::MapErrFuture<A,Req,F,E> as core::future::future::Future>::poll::hf7f0874372db3024
  24:     0x7fbdddf1fed8 - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::h5cde778d7b9e2fad
  25:     0x7fbdddf30bf0 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::h8b6e656b6ab850fe
  26:     0x7fbdde0090f0 - tokio::runtime::task::raw::poll::h3407b21d2abbedf0
  27:     0x7fbdde4cf267 - tokio::task::local::LocalSet::tick::h8a6702fc5875537b
  28:     0x7fbdde129360 - tokio::task::local::LocalSet::run_until::{{closure}}::h41aadbeb0665778b
  29:     0x7fbdde125a05 - std::sys_common::backtrace::__rust_begin_short_backtrace::h714eed4428e92697
  30:     0x7fbdde123d92 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h16834ad1895b807b
  31:     0x7fbdde4b3235 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d93caaa9e044d7b
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  32:     0x7fbdde4b3235 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdde4c57915b40e6d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  33:     0x7fbdde4b3235 - std::sys::unix::thread::Thread::new::thread_start::h6f605c4e9cacf099
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys/unix/thread.rs:108:17
[2023-09-11 14:58:02][DEBUG] starting new connection: https://app.bilibili.com/
[2023-09-11 14:58:02][DEBUG] resolving host="app.bilibili.com"
[2023-09-11 14:58:02][DEBUG] connecting to 103.151.151.4:443
[2023-09-11 14:58:02][DEBUG] connected to 103.151.151.4:443
[2023-09-11 14:58:02][DEBUG] No cached session for DnsName(DnsName(DnsName("app.bilibili.com")))
[2023-09-11 14:58:02][DEBUG] Not resuming any session
[2023-09-11 14:58:02][DEBUG] ALPN protocol is Some(b"h2")
[2023-09-11 14:58:02][DEBUG] Using ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[2023-09-11 14:58:02][DEBUG] Server supports tickets
[2023-09-11 14:58:02][DEBUG] ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp256r1 }
[2023-09-11 14:58:02][DEBUG] Server DNS name is DnsName(DnsName(DnsName("app.bilibili.com")))
[2023-09-11 14:58:02][DEBUG] Session saved
[2023-09-11 14:58:02][DEBUG] binding client connection
[2023-09-11 14:58:02][DEBUG] client connection bound
[2023-09-11 14:58:02][DEBUG] send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
[2023-09-11 14:58:02][DEBUG] Connection; peer=Client
[2023-09-11 14:58:02][DEBUG] send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
[2023-09-11 14:58:02][DEBUG] pooling idle connection for ("https", app.bilibili.com)
[2023-09-11 14:58:02][DEBUG] send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
[2023-09-11 14:58:02][DEBUG] received frame=Settings { flags: (0x0), max_concurrent_streams: 128, initial_window_size: 65536, max_frame_size: 16777215 }
[2023-09-11 14:58:02][DEBUG] send frame=Settings { flags: (0x1: ACK) }
[2023-09-11 14:58:02][DEBUG] received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 2147418112 }
[2023-09-11 14:58:02][DEBUG] received frame=Settings { flags: (0x1: ACK) }
[2023-09-11 14:58:02][DEBUG] received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
[2023-09-11 14:58:02][DEBUG] received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
[2023-09-11 14:58:02][DEBUG] received frame=Data { stream_id: StreamId(1) }
[2023-09-11 14:58:02][DEBUG] [GET WEBPAGE] PROXY false |  -> STATUS CODE: 200
[2023-09-11 14:58:02][DEBUG] [GET WEBPAGE] URL https://app.bilibili.com/x/v2/account/myinfo?access_key=2f7149802e00fddbf412974d19b67891&appkey=1d8b6e7d45233436&build=5360000&mobi_app=android&platform=android&ts=1694444282&sign=4e115d50a26c7a67e255c84e96ed0d1b
[2023-09-11 14:58:02][DEBUG] [UPDATE_CACHE] UID 23579215 | AK 2f7149802e00fddbf412974d19b67891 -> is VIP: true. New user_info cache data: {"code":0,"access_key":"2f7149802e00fddbf412974d19b67891","uid":23579215,"vip_expire_time":1730649600000,"expire_time":1696604282777}
[2023-09-11 14:58:02][DEBUG] send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
[2023-09-11 14:58:02][DEBUG] Connection::poll; connection error error=GoAway(b"", NO_ERROR, Library)
[2023-09-11 14:58:02][DEBUG] Sending warning alert CloseNotify
thread 'actix-server worker 1' panicked at 'called `Option::unwrap()` on a `None` value', src/mods/types.rs:206:26
stack backtrace:
   0:     0x7fbdde4aff90 - std::backtrace_rs::backtrace::libunwind::trace::hbcfab3fd053d4f9c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fbdde4aff90 - std::backtrace_rs::backtrace::trace_unsynchronized::h7e10f1e6f3c9da4a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbdde4aff90 - std::sys_common::backtrace::_print_fmt::h0eb15397837ad542
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fbdde4aff90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf7c1fab2895a69f6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fbdde2135ae - core::fmt::write::h2f4df54048f9b2f6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x7fbdde489bc4 - std::io::Write::write_fmt::he2a3d151c8582691
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x7fbdde4b179f - std::sys_common::backtrace::_print::h99e54e0cdbaf7634
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fbdde4b179f - std::sys_common::backtrace::print::h55b70014ea5d5cc4
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fbdde4b139f - std::panicking::default_hook::{{closure}}::hfd59080aa8766eb0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x7fbdde4b241d - std::panicking::default_hook::h5edea27902e76e98
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x7fbdde4b241d - std::panicking::rust_panic_with_hook::he30378b37a10c21d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x7fbdde4b1eb4 - std::panicking::begin_panic_handler::{{closure}}::h4870022cb9a556d9
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:577:13
  12:     0x7fbdde4b1e4c - std::sys_common::backtrace::__rust_end_short_backtrace::h1c949acb60f0c2aa
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7fbdde4b1e21 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x7fbdddef13c2 - core::panicking::panic_fmt::hc3a21bf3fce4f929
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x7fbdddef14bc - core::panicking::panic::ha93ad6cb648d74fd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
  16:     0x7fbdde1dba68 - biliroaming_rust_server::mods::cache::update_user_info_cache::{{closure}}::hf281284fa33d1594
  17:     0x7fbdde1d203b - biliroaming_rust_server::mods::upstream_res::get_upstream_bili_account_info_rec::{{closure}}::h9d094ba4e9b3e858
  18:     0x7fbdddfa3ab5 - biliroaming_rust_server::mods::user_info::get_user_info::{{closure}}::ha4e74effe6cc0bf8
  19:     0x7fbdddf9481c - biliroaming_rust_server::mods::handler::handle_playurl_request::{{closure}}::hf673c91587eb30ea
  20:     0x7fbdde070a14 - actix_web::handler::handler_service::{{closure}}::{{closure}}::h216788b73de3a415
  21:     0x7fbdde06bda8 - <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}::hab147ca2d10f8436
  22:     0x7fbdde06cdef - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::hcc57d36176248111
  23:     0x7fbdddf0fcb9 - <actix_service::map_err::MapErrFuture<A,Req,F,E> as core::future::future::Future>::poll::hf7f0874372db3024
  24:     0x7fbdddf1fed8 - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::h5cde778d7b9e2fad
  25:     0x7fbdddf30bf0 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::h8b6e656b6ab850fe
  26:     0x7fbdde0090f0 - tokio::runtime::task::raw::poll::h3407b21d2abbedf0
  27:     0x7fbdde4cf267 - tokio::task::local::LocalSet::tick::h8a6702fc5875537b
  28:     0x7fbdde129360 - tokio::task::local::LocalSet::run_until::{{closure}}::h41aadbeb0665778b
  29:     0x7fbdde125a05 - std::sys_common::backtrace::__rust_begin_short_backtrace::h714eed4428e92697
  30:     0x7fbdde123d92 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h16834ad1895b807b
  31:     0x7fbdde4b3235 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d93caaa9e044d7b
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  32:     0x7fbdde4b3235 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdde4c57915b40e6d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  33:     0x7fbdde4b3235 - std::sys::unix::thread::Thread::new::thread_start::h6f605c4e9cacf099
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys/unix/thread.rs:108:17
```

**Comment by hyb-oyqq** [comment]
使用root权限再次运行报错已经更改为
thread 'actix-server worker 6' panicked at 'called `Result::unwrap()` on an `Err` value: Backend(failed to lookup address information: Try again)', /workdir/src/mods/request.rs:151:38

看其他issue说是服务器网络问题，想请教下是网络环境问题还是服务器配置导致的网络问题？

**Comment by hyb-oyqq** [comment]
换了台更老版本的服务器发现也在报错，疑似是黑名单api炸了，暂时先关掉本issue先，等黑名单恢复确认是服务器问题再提起
