### ISSUE TITLE
手动编译失败

### ISSUE THREAD

**Issue by xiaonian233** [pchpub/BiliRoaming-Rust-Server#6]
系统：Ubuntu 20.04 LTS (GNU/Linux 5.4.0-28-generic x86_64) 
Cargo版本：cargo 1.59.0
使用cargo build --profile=fast失败后使用RUST_BACKTRACE=full cargo build --profile=fast
```
error: failed to run custom build command for `openssl-sys v0.9.74`

Caused by:
  process didn't exit successfully: `/root/BiliRoaming-Rust-Server/target/fast/build/openssl-sys-bd79fadc58d77a17/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/root/BiliRoaming-Rust-Server/target/fast/build/openssl-sys-395c635de52eec05/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
  Configuring OpenSSL version 1.1.1q (0x1010111fL) for linux-x86_64
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.22.0+1.1.1q/src/lib.rs:488:39
  stack backtrace:
     0:     0x558e92281166 - std::backtrace_rs::backtrace::libunwind::trace::h909d8dc7fbe5a4dc
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x558e92281166 - std::backtrace_rs::backtrace::trace_unsynchronized::h53796f982c63f683
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x558e92281166 - std::sys_common::backtrace::_print_fmt::hf36cf7879fe9b4bb
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x558e92281166 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he8f52cc46d2e42d0
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x558e922b15cc - core::fmt::write::hdf95362499ef3a33
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/core/src/fmt/mod.rs:1168:17
     5:     0x558e92271b25 - std::io::Write::write_fmt::h41623ec68625ac46
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/io/mod.rs:1660:15
     6:     0x558e9227aac1 - std::sys_common::backtrace::_print::h04f5f3b4507f8e49
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x558e9227aac1 - std::sys_common::backtrace::print::habe477a511c3f42c
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x558e9227aac1 - std::panicking::default_hook::{{closure}}::h2c94e168b7b1bb12
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:211:50
     9:     0x558e9227a6c1 - std::panicking::default_hook::h6a80c87a4f65dbdc
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:228:9
    10:     0x558e9227b011 - std::panicking::rust_panic_with_hook::h7585be41d281db68
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:606:17
    11:     0x558e92281950 - std::panicking::begin_panic_handler::{{closure}}::h7b597c65e0c1b4f5
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:502:13
    12:     0x558e92281294 - std::sys_common::backtrace::__rust_end_short_backtrace::hf1775f5ce06758db
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/sys_common/backtrace.rs:139:18
    13:     0x558e9227aba2 - rust_begin_unwind
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:498:5
    14:     0x558e921c98e1 - core::panicking::panic_fmt::h73493c5597d0fe4c
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/core/src/panicking.rs:116:14
    15:     0x558e921c9973 - core::result::unwrap_failed::ha6a47576b27a465d
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/core/src/result.rs:1690:5
    16:     0x558e9220ac79 - core::result::Result<T,E>::unwrap::h457f1f11ffeb323b
    17:     0x558e922062ce - openssl_src::Build::run_command::h77924df61239069c
    18:     0x558e922057b7 - openssl_src::Build::build::h7577c4c4bc43cfa6
    19:     0x558e921d0b1e - build_script_main::find_vendored::get_openssl::h862cc4fcfd723d7f
    20:     0x558e921cc225 - build_script_main::find_openssl::h27bccccf8bfc3eca
    21:     0x558e921cc31f - build_script_main::main::h81bd281d92ede84e
    22:     0x558e921d1343 - core::ops::function::FnOnce::call_once::h18220c4fa202f847
    23:     0x558e921d1c99 - std::sys_common::backtrace::__rust_begin_short_backtrace::he9049d42cf063abe
    24:     0x558e921d16c9 - std::rt::lang_start::{{closure}}::h422d67badeed8e9a
    25:     0x558e9226f441 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7aae6315816edcf2
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/core/src/ops/function.rs:259:13
    26:     0x558e9226f441 - std::panicking::try::do_call::hf4e3cb0198f3a934
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:406:40
    27:     0x558e9226f441 - std::panicking::try::hf88849252e9a86ea
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:370:19
    28:     0x558e9226f441 - std::panic::catch_unwind::hfbc773ffb56d78b3
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panic.rs:133:14
    29:     0x558e9226f441 - std::rt::lang_start_internal::{{closure}}::h24888b63d9245773
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/rt.rs:128:48
    30:     0x558e9226f441 - std::panicking::try::do_call::h3d6ee7e80f909fe0
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:406:40
    31:     0x558e9226f441 - std::panicking::try::h303fd780ada5a5f8
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panicking.rs:370:19
    32:     0x558e9226f441 - std::panic::catch_unwind::h17064119db8151db
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/panic.rs:133:14
    33:     0x558e9226f441 - std::rt::lang_start_internal::hfc7946e623485e28
                                 at /build/rustc-K9H5El/rustc-1.59.0+dfsg1~ubuntu1~llvm/library/std/src/rt.rs:128:20
    34:     0x558e921d16b1 - std::rt::lang_start::h9c6df88a3816b52f
    35:     0x558e921d0323 - main
    36:     0x7ffa9e1cc083 - __libc_start_main
    37:     0x558e921c9fee - _start
    38:                0x0 - <unknown>

```

**Comment by KimmyXYC** [comment]
Linux要装openssl-devel

**Comment by xiaonian233** [comment]
> Linux要装openssl-devel

ubuntu没有openssl-devel
一番搜索后ubuntu安装
apt install openssl
apt install libssl-dev
但是仍然有错误，已经执行过清理cargo缓存

**Comment by pchpub** [comment]
使用最新源码再次尝试

**Comment by xiaonian233** [comment]
可以了，本地+全局梯子成功了，昨天在vps编译的绷不住了

**Comment by KimmyXYC** [comment]
> 可以了，本地+全局梯子成功了，昨天在vps编译的绷不住了

可以添加国内源 默认是从国外源拉取依赖的

**Comment by xiaonian233** [comment]
在hk机子上拉取的估计是系统问题吧
